import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Compass, Map, Sparkles, Target } from "lucide-react";

export const metadata: Metadata = {
  title: "AI Career Roadmap & Career Planning",
  description: "Build a practical AI career roadmap around your goals, target roles, location and experience. Compare career paths instead of guessing your next move.",
  keywords: ["AI career roadmap", "career roadmap", "career planning tool", "career path planner", "career change planner", "AI career coach"],
  alternates: { canonical: "/prepare-ai" },
  openGraph: { title: "AI Career Roadmap & Career Planning | Flint.ai", description: "Figure out your next career move with a roadmap built around your actual goals.", url: "/prepare-ai", images: [{ url: "/og-image.svg", width: 1200, height: 630, alt: "Flint.ai career roadmap" }] },
};

export default function PrepareAiLanding() {
  const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Flint.ai PrepareAI", applicationCategory: "BusinessApplication", operatingSystem: "Web", description: "AI career roadmap and career planning tool.", url: "https://flintai.vercel.app/prepare-ai" };
  return <main className="min-h-screen px-5 pb-24 pt-28"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="mx-auto max-w-5xl"><section className="mx-auto max-w-4xl text-center"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-border/60 bg-card/70 px-4 py-2 text-xs font-semibold"><Sparkles className="h-3.5 w-3.5" /> Career planning without the crystal ball</div><h1 className="text-4xl font-black tracking-tight sm:text-5xl md:text-7xl">You know where you want to go. <span className="bg-gradient-to-r from-violet-400 via-cyan-300 to-violet-400 bg-clip-text text-transparent">Now map it.</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-muted-foreground md:text-lg">Tell Flint what you want, where you are starting from, and what matters to you. Get a practical route with milestones, skills, resources and trade-offs.</p><Link href="/prepareAI" className="mt-8 inline-flex items-center gap-2 rounded-full bg-foreground px-7 py-3.5 text-sm font-semibold text-background transition hover:opacity-90">Build my roadmap <ArrowRight className="h-4 w-4" /></Link></section><section className="mt-20 grid gap-4 md:grid-cols-3">{[[Target,"Pick a target","Choose a role, industry, market or direction — tech is not a requirement."],[Compass,"Know your starting point","Your current skills and experience shape the route."],[Map,"Get the route","Turn the gap between now and next into steps you can actually take."]].map(([Icon,title,text])=><div key={title as string} className="rounded-3xl border border-border/60 bg-card/60 p-6"><div className="mb-5 grid h-10 w-10 place-items-center rounded-xl bg-muted"><Icon className="h-5 w-5"/></div><h2 className="text-lg font-bold">{title as string}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text as string}</p></div>)}</section><section className="mt-20 rounded-3xl border border-border/60 bg-card/50 p-7 md:p-10"><h2 className="text-2xl font-bold">A career plan should leave you with moves, not motivation quotes.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground">Whether you are a student choosing a direction, a professional changing fields, or someone trying to break into a new market, the useful question is the same: what should I do next? Flint turns that question into a route you can revisit and compare.</p></section></div></main>;
}
