import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, FileText, ScanSearch, Target } from "lucide-react";

export const metadata: Metadata = {
  title: "Free ATS Resume Checker & Resume Score",
  description: "Check your resume against ATS-style hiring signals, get an ATS resume score, spot missing keywords, and see what to fix before you apply.",
  keywords: ["ATS resume checker", "free ATS resume checker", "ATS resume score", "resume ATS score", "ATS resume scanner", "resume checker", "resume analyzer"],
  alternates: { canonical: "/resume-ai" },
  openGraph: { title: "Free ATS Resume Checker & Resume Score", description: "Upload your resume, see an ATS-style score, and get practical fixes before you hit Apply.", url: "/resume-ai", images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "Flint.ai ATS resume checker" }] },
};

const schema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Flint.ai ATS Resume Checker", applicationCategory: "BusinessApplication", operatingSystem: "Web", url: "https://flintai.vercel.app/resume-ai", description: "ATS-style resume scoring and practical resume improvement suggestions.", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } };

export default function ResumeAiLanding() {
  return <main className="min-h-screen px-5 pb-24 pt-28 md:px-8 md:pt-36"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="mx-auto max-w-5xl"><section className="mx-auto max-w-3xl text-center"><div className="mx-auto mb-5 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-3 py-1.5 text-xs font-semibold text-primary"><ScanSearch className="h-3.5 w-3.5" /> ATS resume checker</div><h1 className="text-4xl font-black tracking-[-0.04em] md:text-6xl">Your resume has one job. Get you noticed.</h1><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-muted-foreground md:text-lg">Upload your resume, pick the role you want, and get an ATS resume score plus the stuff worth fixing before you apply.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><Link href="/resumeAI" className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-foreground px-7 text-sm font-semibold text-background transition hover:opacity-90">Check my resume <ArrowRight className="h-4 w-4" /></Link><span className="text-xs text-muted-foreground">One free scan to start.</span></div></section><section className="mt-16 grid gap-4 md:grid-cols-3">{[[FileText,"ATS score","A simple 0–100 signal so you know where you stand."],[Target,"Role-aware","The check is built around the job you actually want."],[Check,"Useful fixes","Keywords, structure, gaps and clear next steps — not vague advice."]].map(([Icon,title,text])=>{const I=Icon as typeof FileText;return <div key={title as string} className="rounded-3xl border border-border/60 bg-card/70 p-6"><div className="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-muted"><I className="h-5 w-5" /></div><h2 className="font-bold">{title as string}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text as string}</p></div>})}</section><section className="mt-10 rounded-3xl border border-border/60 bg-card/60 p-6 md:p-8"><h2 className="text-xl font-bold">What does an ATS resume score mean?</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground">Applicant tracking systems help employers sort and search applications. Flint checks role keywords, structure, clarity and relevant evidence, then turns the result into fixes you can actually make.</p></section></div></main>;
}
