"use client";
import React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";

export default function Footer() {
  const currentYear = new Date().getFullYear();
  const pathname = usePathname();
  const footerSections = [
    { title: "Explore", links: [{ label: "Home", href: "/" }, { label: "ATS Resume Scanner", href: "/resume-ai" }, { label: "Career Roadmaps", href: "/prepare-ai" }, { label: "LinkedIn Optimizer", href: "/linkedin-optimizer" }, { label: "Premium", href: "/subscribe" }] },
    { title: "Legal", links: [{ label: "User Agreement", href: "/user-agreement" }, { label: "Terms of Service", href: "/terms" }] },
    { title: "Support", links: [{ label: "Contact us", href: "mailto:help@flint.ai" }, { label: "Raise an issue", href: "https://github.com/friedavocadoes/flint.ai/issues" }] },
  ];
  const socialLinks = [{ icon: "github", href: "https://github.com/friedavocadoes", ariaLabel: "GitHub" }, { icon: "x", href: "https://twitter.com/home?lang=en", ariaLabel: "X" }, { icon: "instagram", href: "https://instagram.com/gnawthm", ariaLabel: "Instagram" }, { icon: "linkedin", href: "https://www.linkedin.com/in/gautham-madhu/", ariaLabel: "LinkedIn" }, { icon: "mail", href: "mailto:77gautham@gmail.com", ariaLabel: "Email" }];
  return <footer className={`bg-stone-200 dark:bg-[#0c0c0d] py-16 px-10 md:px-40 border-t border-stone-300 dark:border-gray-800/20 ${pathname === "/prepareAI" ? "hidden" : ""}`}><div className="container mx-auto"><div className="grid grid-cols-1 md:grid-cols-5 gap-10"><div className="space-y-4"><h3 className="text-xl font-semibold text-black dark:text-white">Flint.ai</h3><p className="text-stone-700 dark:text-gray-400 text-sm max-w-xs">Career tools for figuring out what&apos;s next — from your first role to your next big move.</p><div className="flex space-x-4 mt-6">{socialLinks.map((link) => <a key={link.icon} href={link.href} aria-label={link.ariaLabel} target="_blank" rel="noreferrer" className="w-8 h-8 flex items-center justify-center border border-gray-700 rounded-full text-stone-700 dark:text-gray-400 hover:text-black dark:hover:text-white dark:hover:border-gray-500 transition-colors"><SocialIcon name={link.icon} /></a>)}</div></div>{footerSections.map((section) => <div key={section.title} className="space-y-4"><h4 className="text-sm font-medium text-black dark:text-gray-500">{section.title}</h4><ul className="space-y-2">{section.links.map((link) => <li key={link.label}><Link href={link.href} className="text-stone-700 dark:text-gray-400 hover:text-blue-800 dark:hover:text-white transition-colors">{link.label}</Link></li>)}</ul></div>)}<div className="space-y-4"><h4 className="text-sm font-medium text-stone-700 dark:text-gray-500">Need a hand?</h4><a href="mailto:help@flint.ai" className="text-indigo-700 dark:text-blue-400 hover:text-blue-300 flex items-center space-x-2 transition-colors"><span>help@flint.ai</span></a></div></div><div className="mt-16 pt-6 border-t border-gray-800/20 text-gray-500 text-sm text-center"><p>© {currentYear} Flint.ai. Built for people figuring out what&apos;s next.</p></div></div></footer>;
}

export function SocialIcon({ name }: { name: string }) { if (name === "github") return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" /><path d="M9 18c-4.51 2-5-2-7-2" /></svg>; if (name === "x") return <span className="text-xs font-bold">𝕏</span>; if (name === "instagram") return <span className="text-xs font-bold">◎</span>; if (name === "linkedin") return <span className="text-xs font-bold">in</span>; if (name === "mail") return <span className="text-xs">✉</span>; return null; }
