import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Flint.ai terms covering the service, purchases, Premium access, cancellations, refunds and AI limitations.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return <main className="mx-auto max-w-3xl px-5 pb-24 pt-28"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Flint.ai legal</p><h1 className="mt-2 text-4xl font-bold tracking-tight">Terms of Service</h1><p className="mt-2 text-xs text-muted-foreground">Last updated 26 August 2026</p><article className="prose prose-invert mt-10 max-w-none prose-headings:mt-8 prose-p:text-muted-foreground"><h2>1. Service</h2><p>Flint.ai is a career-development software product providing AI-assisted career planning, resume analysis and professional-profile guidance.</p><h2>2. Purchases</h2><p>One-time generation purchases provide the purchased generation for the feature displayed at checkout. Premium provides the features and access period displayed on the subscription page at the time of purchase.</p><h2>3. Cancellation</h2><p>Premium is currently sold as a prepaid access purchase. If cancellation is available, confirming cancellation ends the current Premium entitlement immediately. Cancellation does not create a refund for unused time unless a refund is required by applicable law.</p><h2>4. Refunds</h2><p>Because AI generations are digital services that can be consumed immediately, completed generations may not be refundable except where required by applicable law. We may review duplicate, failed or clearly erroneous charges on request.</p><h2>5. AI limitations</h2><p>Flint.ai does not guarantee employment outcomes, ATS scores, salary estimates, market availability, immigration outcomes, or the accuracy of any AI-generated recommendation.</p><h2>6. Changes</h2><p>We may update these terms as Flint.ai evolves. Material changes will be communicated through the service where appropriate.</p><h2>7. Legal review</h2><p>These product terms are provided as a working product document and should be reviewed and adapted for the legal entity, payment setup and jurisdictions in which Flint.ai operates before commercial launch.</p></article></main>;
}
